# Site settings
title: Will Richardson
author: Will Richardson
author_url: https://twitter.com/willhbr
email: william.hamish+spam@gmail.com
description: "Programming language connoisseur. Beard owner. Software engineer."
baseurl: ""
url: "https://willhbr.net"
human_url: "willhbr.net"
twitter_username: willhbr
github_username:  willhbr
paginate: 10
paginate_path: "/page/:num"
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
