title: Will Richardson
author: Will Richardson
author_url: https://willhbr.net/me
mastodon_url: https://ruby.social/@willhbr
description: ""
baseurl: ""
url: "https://willhbr.net"
human_url: "willhbr.net"
paginate: 10
paginate_path: "/page/:num"
plugins: [jekyll-paginate]

feeds:
  rss_url: "/feed.xml"
  json_url: "/feed.json"
  json_include_text: false

date_format: "%B %-d, %Y"
timezone: Australia/Sydney

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

sass:
  style: compressed

include:
  - .well-known

exclude:
  - CNAME
  - Containerfile.local
  - Gemfile
  - Gemfile.lock
  - README.md
  - pods.yaml

webfinger:
  subject: "acct:willhbr@ruby.social"
  aliases": ["https://ruby.social/@willhbr", "https://ruby.social/users/willhbr"]
  links:
    - rel: "http://webfinger.net/rel/profile-page"
      type: "text/html"
      href: "https://ruby.social/@willhbr"
    - rel: "self"
      type: "application/activity+json"
      href: "https://ruby.social/users/willhbr"
    - rel: "http://ostatus.org/schema/1.0/subscribe"
      template: "https://ruby.social/authorize_interaction?uri={uri}"
