# Site settings
title: Will Richardson
author: Will Richardson
email: william.hamish+spam@gmail.com
description: "Independent app & web developer. Student. Tech enthusiast."
url: "http://javanut.net"
human_url: "javanut.net"
twitter_username: javanut13
github_username:  javanut13
paginate: 10
paginate_path: "/blog/page-:num"
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
