# Site settings
title: Will Richardson
email: william.hamish+spam@gmail.com
description: "Uneducated rant on stuff."
baseurl: ""
url: "http://javanut13.github.io"
human_url: "javanut13.github.io"
twitter_username: javanut13
github_username:  javanut13
paginate: 10
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments