# Site settings
title: Will Richardson
author: Will Richardson
author_url: https://willhbr.net/me
description: ""
baseurl: ""
url: "https://willhbr.net"
human_url: "willhbr.net"
twitter_username: willhbr
github_username:  willhbr
paginate: 10
paginate_path: "/page/:num"
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

include:
  - .well-known
